server: "hub-cloud.browserstack.com"
user: "christopherlim5"
key: "WqvvGLWcneotxHJzwvKy"

common_caps:
  "build": "rspec-browserstack"
  "browserstack.debug": true

browser_caps:
  -
    "browser": "chrome"
    "browserstack.local": true
